//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fixStrategyEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fixStrategyEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="configure"/>
 *     &lt;enumeration value="combination"/>
 *     &lt;enumeration value="disable"/>
 *     &lt;enumeration value="enable"/>
 *     &lt;enumeration value="patch"/>
 *     &lt;enumeration value="policy"/>
 *     &lt;enumeration value="restrict"/>
 *     &lt;enumeration value="update"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "fixStrategyEnumType")
@XmlEnum
public enum FixStrategyEnumType {


    /**
     * Strategy not defined
     *                         (default)
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),

    /**
     * Adjust target
     *                         configuration/settings
     * 
     */
    @XmlEnumValue("configure")
    CONFIGURE("configure"),

    /**
     * Combination of two or more
     *                         approaches
     * 
     */
    @XmlEnumValue("combination")
    COMBINATION("combination"),

    /**
     * Turn off or uninstall a target component
     *                     
     * 
     */
    @XmlEnumValue("disable")
    DISABLE("disable"),

    /**
     * Turn on or install a target
     *                         component
     * 
     */
    @XmlEnumValue("enable")
    ENABLE("enable"),

    /**
     * Apply a patch, hotfix, update,
     *                         etc.
     * 
     */
    @XmlEnumValue("patch")
    PATCH("patch"),

    /**
     * Remediation requires out-of-band adjustments to
     *                         policies or procedures
     * 
     */
    @XmlEnumValue("policy")
    POLICY("policy"),

    /**
     * Adjust permissions, access rights, filters, or
     *                         other access restrictions
     * 
     */
    @XmlEnumValue("restrict")
    RESTRICT("restrict"),

    /**
     * Install, upgrade or update the
     *                         system
     * 
     */
    @XmlEnumValue("update")
    UPDATE("update");
    private final String value;

    FixStrategyEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FixStrategyEnumType fromValue(String v) {
        for (FixStrategyEnumType c: FixStrategyEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
