//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:Profile> element, which
 *                 holds a specific tailoring of the <xccdf:Benchmark>. The main part of an
 *                 <xccdf:Profile> is the selectors: <xccdf:select>,
 *                 <xccdf:set-value>, <xccdf:set-complex-value>, <xccdf:refine-rule>,
 *                 and <xccdf:refine-value>. An <xccdf:Profile> may also be signed with an
 *                 XML-Signature. 
 * 
 * <p>Java class for profileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://checklists.nist.gov/xccdf/1.2}status" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dc-status" type="{http://checklists.nist.gov/xccdf/1.2}dc-statusType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="version" type="{http://checklists.nist.gov/xccdf/1.2}versionType" minOccurs="0"/>
 *         &lt;element name="title" type="{http://checklists.nist.gov/xccdf/1.2}textWithSubType" maxOccurs="unbounded"/>
 *         &lt;element name="description" type="{http://checklists.nist.gov/xccdf/1.2}htmlTextWithSubType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://checklists.nist.gov/xccdf/1.2}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="platform" type="{http://checklists.nist.gov/xccdf/1.2}overrideableCPE2idrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="select" type="{http://checklists.nist.gov/xccdf/1.2}profileSelectType" minOccurs="0"/>
 *           &lt;element name="set-complex-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetComplexValueType" minOccurs="0"/>
 *           &lt;element name="set-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetValueType" minOccurs="0"/>
 *           &lt;element name="refine-value" type="{http://checklists.nist.gov/xccdf/1.2}profileRefineValueType" minOccurs="0"/>
 *           &lt;element name="refine-rule" type="{http://checklists.nist.gov/xccdf/1.2}profileRefineRuleType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="metadata" type="{http://checklists.nist.gov/xccdf/1.2}metadataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}profileIdType" />
 *       &lt;attribute name="prohibitChanges" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="note-tag" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profileType", propOrder = {
    "title",
})
public class ProfileType {

    @XmlElement(required = true)
    protected String title;
    @XmlAttribute(name = "idref", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextWithSubType }
     * 
     * 
     */
    public String getTitle() {
        if (title == null) {
            title = "";
        }
        return this.title;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
