//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for severityEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="severityEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="info"/>
 *     &lt;enumeration value="low"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="high"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "severityEnumType")
@XmlEnum
public enum SeverityEnumType {


    /**
     * Severity not defined (default).
     *                     
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),

    /**
     * <xccdf:Rule> is informational and failure
     *                         does not represent a problem. 
     * 
     */
    @XmlEnumValue("info")
    INFO("info"),

    /**
     * Not a serious problem. 
     * 
     */
    @XmlEnumValue("low")
    LOW("low"),

    /**
     * Fairly serious problem. 
     * 
     */
    @XmlEnumValue("medium")
    MEDIUM("medium"),

    /**
     * A grave or critical problem.
     *                     
     * 
     */
    @XmlEnumValue("high")
    HIGH("high");
    private final String value;

    SeverityEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SeverityEnumType fromValue(String v) {
        for (SeverityEnumType c: SeverityEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
