//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:fixtext> element, which
 *                 contains data that describes how to bring a target system into compliance with an
 *                 <xccdf:Rule>. Each <xccdf:fixtext> element may be associated with one or
 *                 more <xccdf:fix> elements through the @fixref attribute. The body holds
 *                 explanatory text about the fix procedures.
 * 
 * <p>Java class for fixTextType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fixTextType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://checklists.nist.gov/xccdf/1.2}htmlTextWithSubType">
 *       &lt;attribute name="fixref" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="reboot" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" />
 *       &lt;attribute name="strategy" type="{http://checklists.nist.gov/xccdf/1.2}fixStrategyEnumType" default="unknown" />
 *       &lt;attribute name="disruption" type="{http://checklists.nist.gov/xccdf/1.2}ratingEnumType" default="unknown" />
 *       &lt;attribute name="complexity" type="{http://checklists.nist.gov/xccdf/1.2}ratingEnumType" default="unknown" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fixTextType")
public class FixTextType
    extends HtmlTextWithSubType
{

    @XmlAttribute(name = "fixref")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String fixref;
    @XmlAttribute(name = "reboot")
    protected Boolean reboot;
    @XmlAttribute(name = "strategy")
    protected FixStrategyEnumType strategy;
    @XmlAttribute(name = "disruption")
    protected RatingEnumType disruption;
    @XmlAttribute(name = "complexity")
    protected RatingEnumType complexity;

    /**
     * Gets the value of the fixref property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixref() {
        return fixref;
    }

    /**
     * Sets the value of the fixref property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixref(String value) {
        this.fixref = value;
    }

    /**
     * Gets the value of the reboot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReboot() {
        if (reboot == null) {
            return false;
        } else {
            return reboot;
        }
    }

    /**
     * Sets the value of the reboot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReboot(Boolean value) {
        this.reboot = value;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * @return
     *     possible object is
     *     {@link FixStrategyEnumType }
     *     
     */
    public FixStrategyEnumType getStrategy() {
        if (strategy == null) {
            return FixStrategyEnumType.UNKNOWN;
        } else {
            return strategy;
        }
    }

    /**
     * Sets the value of the strategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixStrategyEnumType }
     *     
     */
    public void setStrategy(FixStrategyEnumType value) {
        this.strategy = value;
    }

    /**
     * Gets the value of the disruption property.
     * 
     * @return
     *     possible object is
     *     {@link RatingEnumType }
     *     
     */
    public RatingEnumType getDisruption() {
        if (disruption == null) {
            return RatingEnumType.UNKNOWN;
        } else {
            return disruption;
        }
    }

    /**
     * Sets the value of the disruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingEnumType }
     *     
     */
    public void setDisruption(RatingEnumType value) {
        this.disruption = value;
    }

    /**
     * Gets the value of the complexity property.
     * 
     * @return
     *     possible object is
     *     {@link RatingEnumType }
     *     
     */
    public RatingEnumType getComplexity() {
        if (complexity == null) {
            return RatingEnumType.UNKNOWN;
        } else {
            return complexity;
        }
    }

    /**
     * Sets the value of the complexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingEnumType }
     *     
     */
    public void setComplexity(RatingEnumType value) {
        this.complexity = value;
    }

}
