//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:fix> element. The body
 *                 of this element contains a command string, script, or other system modification
 *                 statement that, if executed on the target system, can bring it into full, or at
 *                 least better, compliance with this <xccdf:Rule>. 
 * 
 * <p>Java class for fixType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fixType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="sub" type="{http://checklists.nist.gov/xccdf/1.2}subType"/>
 *         &lt;element name="instance" type="{http://checklists.nist.gov/xccdf/1.2}instanceFixType"/>
 *       &lt;/choice>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="reboot" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" />
 *       &lt;attribute name="strategy" type="{http://checklists.nist.gov/xccdf/1.2}fixStrategyEnumType" default="unknown" />
 *       &lt;attribute name="disruption" type="{http://checklists.nist.gov/xccdf/1.2}ratingEnumType" default="unknown" />
 *       &lt;attribute name="complexity" type="{http://checklists.nist.gov/xccdf/1.2}ratingEnumType" default="unknown" />
 *       &lt;attribute name="system" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="platform" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fixType", propOrder = {
    "content"
})
public class FixType {

    @XmlElementRefs({
        @XmlElementRef(name = "sub", namespace = "http://checklists.nist.gov/xccdf/1.2", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "instance", namespace = "http://checklists.nist.gov/xccdf/1.2", type = JAXBElement.class, required = false)
    })
    @XmlMixed
    protected List<Serializable> content;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String id;
    @XmlAttribute(name = "reboot")
    protected Boolean reboot;
    @XmlAttribute(name = "strategy")
    protected FixStrategyEnumType strategy;
    @XmlAttribute(name = "disruption")
    protected RatingEnumType disruption;
    @XmlAttribute(name = "complexity")
    protected RatingEnumType complexity;
    @XmlAttribute(name = "system")
    @XmlSchemaType(name = "anyURI")
    protected String system;
    @XmlAttribute(name = "platform")
    @XmlSchemaType(name = "anyURI")
    protected String platform;

    /**
     *  Data type for the <xccdf:fix> element. The body
     *                 of this element contains a command string, script, or other system modification
     *                 statement that, if executed on the target system, can bring it into full, or at
     *                 least better, compliance with this <xccdf:Rule>. Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SubType }{@code >}
     * {@link JAXBElement }{@code <}{@link InstanceFixType }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the reboot property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReboot() {
        if (reboot == null) {
            return false;
        } else {
            return reboot;
        }
    }

    /**
     * Sets the value of the reboot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReboot(Boolean value) {
        this.reboot = value;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * @return
     *     possible object is
     *     {@link FixStrategyEnumType }
     *     
     */
    public FixStrategyEnumType getStrategy() {
        if (strategy == null) {
            return FixStrategyEnumType.UNKNOWN;
        } else {
            return strategy;
        }
    }

    /**
     * Sets the value of the strategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link FixStrategyEnumType }
     *     
     */
    public void setStrategy(FixStrategyEnumType value) {
        this.strategy = value;
    }

    /**
     * Gets the value of the disruption property.
     * 
     * @return
     *     possible object is
     *     {@link RatingEnumType }
     *     
     */
    public RatingEnumType getDisruption() {
        if (disruption == null) {
            return RatingEnumType.UNKNOWN;
        } else {
            return disruption;
        }
    }

    /**
     * Sets the value of the disruption property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingEnumType }
     *     
     */
    public void setDisruption(RatingEnumType value) {
        this.disruption = value;
    }

    /**
     * Gets the value of the complexity property.
     * 
     * @return
     *     possible object is
     *     {@link RatingEnumType }
     *     
     */
    public RatingEnumType getComplexity() {
        if (complexity == null) {
            return RatingEnumType.UNKNOWN;
        } else {
            return complexity;
        }
    }

    /**
     * Sets the value of the complexity property.
     * 
     * @param value
     *     allowed object is
     *     {@link RatingEnumType }
     *     
     */
    public void setComplexity(RatingEnumType value) {
        this.complexity = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystem(String value) {
        this.system = value;
    }

    /**
     * Gets the value of the platform property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatform(String value) {
        this.platform = value;
    }

}
