//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Type for an <xccdf:instance> element in an
 *                 <xccdf:rule-result>. The content is a string, but the element may also have
 *                 two attributes: @context and @parentContext. Both attributes are intended to provide
 *                 hints as to the nature of the substituted content. This body of this type records
 *                 the details of the target system instance for multiply instantiated
 *                 <xccdf:Rule> elements. 
 * 
 * <p>Java class for instanceResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="instanceResultType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *       &lt;attribute name="context" type="{http://www.w3.org/2001/XMLSchema}string" default="undefined" />
 *       &lt;attribute name="parentContext" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "instanceResultType", propOrder = {
    "value"
})
public class InstanceResultType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "context")
    protected String context;
    @XmlAttribute(name = "parentContext")
    protected String parentContext;

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the context property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContext() {
        if (context == null) {
            return "undefined";
        } else {
            return context;
        }
    }

    /**
     * Sets the value of the context property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContext(String value) {
        this.context = value;
    }

    /**
     * Gets the value of the parentContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentContext() {
        return parentContext;
    }

    /**
     * Sets the value of the parentContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentContext(String value) {
        this.parentContext = value;
    }

}
