//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for msgSevEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="msgSevEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="warning"/>
 *     &lt;enumeration value="info"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "msgSevEnumType")
@XmlEnum
public enum MsgSevEnumType {


    /**
     * Denotes a serious problem identified; test did
     *                         not run. 
     * 
     */
    @XmlEnumValue("error")
    ERROR("error"),

    /**
     * Denotes a possible issue; test may not have
     *                         run. 
     * 
     */
    @XmlEnumValue("warning")
    WARNING("warning"),

    /**
     * Denotes important information about the tests.
     *                     
     * 
     */
    @XmlEnumValue("info")
    INFO("info");
    private final String value;

    MsgSevEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MsgSevEnumType fromValue(String v) {
        for (MsgSevEnumType c: MsgSevEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
