//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the xccdfClasses package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Item_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Item");
    private final static QName _Group_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Group");
    private final static QName _Value_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Value");
    private final static QName _TestResult_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "TestResult");
    private final static QName _Rule_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Rule");
    private final static QName _Profile_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Profile");
    private final static QName _Tailoring_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "Tailoring");
    private final static QName _ProfileNoteTypeSub_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "sub");
    private final static QName _TestResultTypeTargetIdRef_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "target-id-ref");
    private final static QName _FixTypeInstance_QNAME = new QName("http://checklists.nist.gov/xccdf/1.2", "instance");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: xccdfClasses
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GroupType }
     * 
     */
    public GroupType createGroupType() {
        return new GroupType();
    }

    /**
     * Create an instance of {@link Benchmark }
     * 
     */
    public Benchmark createBenchmark() {
        return new Benchmark();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link DcStatusType }
     * 
     */
    public DcStatusType createDcStatusType() {
        return new DcStatusType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link HtmlTextWithSubType }
     * 
     */
    public HtmlTextWithSubType createHtmlTextWithSubType() {
        return new HtmlTextWithSubType();
    }

    /**
     * Create an instance of {@link NoticeType }
     * 
     */
    public NoticeType createNoticeType() {
        return new NoticeType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link PlainTextType }
     * 
     */
    public PlainTextType createPlainTextType() {
        return new PlainTextType();
    }

    /**
     * Create an instance of {@link CPE2IdrefType }
     * 
     */
    public CPE2IdrefType createCPE2IdrefType() {
        return new CPE2IdrefType();
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link MetadataType }
     * 
     */
    public MetadataType createMetadataType() {
        return new MetadataType();
    }

    /**
     * Create an instance of {@link Model }
     * 
     */
    public Model createModel() {
        return new Model();
    }

    /**
     * Create an instance of {@link ParamType }
     * 
     */
    public ParamType createParamType() {
        return new ParamType();
    }

    /**
     * Create an instance of {@link ProfileType }
     * 
     */
    public ProfileType createProfileType() {
        return new ProfileType();
    }

    /**
     * Create an instance of {@link ValueType }
     * 
     */
    public ValueType createValueType() {
        return new ValueType();
    }

    /**
     * Create an instance of {@link RuleType }
     * 
     */
    public RuleType createRuleType() {
        return new RuleType();
    }

    /**
     * Create an instance of {@link TestResultType }
     * 
     */
    public TestResultType createTestResultType() {
        return new TestResultType();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link TailoringType }
     * 
     */
    public TailoringType createTailoringType() {
        return new TailoringType();
    }

    /**
     * Create an instance of {@link TextWithSubType }
     * 
     */
    public TextWithSubType createTextWithSubType() {
        return new TextWithSubType();
    }

    /**
     * Create an instance of {@link ComplexCheckType }
     * 
     */
    public ComplexCheckType createComplexCheckType() {
        return new ComplexCheckType();
    }

    /**
     * Create an instance of {@link ScoreType }
     * 
     */
    public ScoreType createScoreType() {
        return new ScoreType();
    }

    /**
     * Create an instance of {@link OverrideableCPE2IdrefType }
     * 
     */
    public OverrideableCPE2IdrefType createOverrideableCPE2IdrefType() {
        return new OverrideableCPE2IdrefType();
    }

    /**
     * Create an instance of {@link CheckExportType }
     * 
     */
    public CheckExportType createCheckExportType() {
        return new CheckExportType();
    }

    /**
     * Create an instance of {@link TailoringReferenceType }
     * 
     */
    public TailoringReferenceType createTailoringReferenceType() {
        return new TailoringReferenceType();
    }

    /**
     * Create an instance of {@link ProfileSelectType }
     * 
     */
    public ProfileSelectType createProfileSelectType() {
        return new ProfileSelectType();
    }

    /**
     * Create an instance of {@link ProfileRefineRuleType }
     * 
     */
    public ProfileRefineRuleType createProfileRefineRuleType() {
        return new ProfileRefineRuleType();
    }

    /**
     * Create an instance of {@link InstanceFixType }
     * 
     */
    public InstanceFixType createInstanceFixType() {
        return new InstanceFixType();
    }

    /**
     * Create an instance of {@link MessageType }
     * 
     */
    public MessageType createMessageType() {
        return new MessageType();
    }

    /**
     * Create an instance of {@link SelStringType }
     * 
     */
    public SelStringType createSelStringType() {
        return new SelStringType();
    }

    /**
     * Create an instance of {@link TargetFactsType }
     * 
     */
    public TargetFactsType createTargetFactsType() {
        return new TargetFactsType();
    }

    /**
     * Create an instance of {@link CheckContentType }
     * 
     */
    public CheckContentType createCheckContentType() {
        return new CheckContentType();
    }

    /**
     * Create an instance of {@link RuleResultType }
     * 
     */
    public RuleResultType createRuleResultType() {
        return new RuleResultType();
    }

    /**
     * Create an instance of {@link TailoringBenchmarkReferenceType }
     * 
     */
    public TailoringBenchmarkReferenceType createTailoringBenchmarkReferenceType() {
        return new TailoringBenchmarkReferenceType();
    }

    /**
     * Create an instance of {@link CheckType }
     * 
     */
    public CheckType createCheckType() {
        return new CheckType();
    }

    /**
     * Create an instance of {@link WarningType }
     * 
     */
    public WarningType createWarningType() {
        return new WarningType();
    }

    /**
     * Create an instance of {@link UriRefType }
     * 
     */
    public UriRefType createUriRefType() {
        return new UriRefType();
    }

    /**
     * Create an instance of {@link ProfileSetValueType }
     * 
     */
    public ProfileSetValueType createProfileSetValueType() {
        return new ProfileSetValueType();
    }

    /**
     * Create an instance of {@link FactType }
     * 
     */
    public FactType createFactType() {
        return new FactType();
    }

    /**
     * Create an instance of {@link InstanceResultType }
     * 
     */
    public InstanceResultType createInstanceResultType() {
        return new InstanceResultType();
    }

    /**
     * Create an instance of {@link HtmlTextType }
     * 
     */
    public HtmlTextType createHtmlTextType() {
        return new HtmlTextType();
    }

    /**
     * Create an instance of {@link ProfileNoteType }
     * 
     */
    public ProfileNoteType createProfileNoteType() {
        return new ProfileNoteType();
    }

    /**
     * Create an instance of {@link SubType }
     * 
     */
    public SubType createSubType() {
        return new SubType();
    }

    /**
     * Create an instance of {@link CheckContentRefType }
     * 
     */
    public CheckContentRefType createCheckContentRefType() {
        return new CheckContentRefType();
    }

    /**
     * Create an instance of {@link FixType }
     * 
     */
    public FixType createFixType() {
        return new FixType();
    }

    /**
     * Create an instance of {@link CheckImportType }
     * 
     */
    public CheckImportType createCheckImportType() {
        return new CheckImportType();
    }

    /**
     * Create an instance of {@link ComplexValueType }
     * 
     */
    public ComplexValueType createComplexValueType() {
        return new ComplexValueType();
    }

    /**
     * Create an instance of {@link SelComplexValueType }
     * 
     */
    public SelComplexValueType createSelComplexValueType() {
        return new SelComplexValueType();
    }

    /**
     * Create an instance of {@link SelChoicesType }
     * 
     */
    public SelChoicesType createSelChoicesType() {
        return new SelChoicesType();
    }

    /**
     * Create an instance of {@link OverrideType }
     * 
     */
    public OverrideType createOverrideType() {
        return new OverrideType();
    }

    /**
     * Create an instance of {@link ProfileRefineValueType }
     * 
     */
    public ProfileRefineValueType createProfileRefineValueType() {
        return new ProfileRefineValueType();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link IdentType }
     * 
     */
    public IdentType createIdentType() {
        return new IdentType();
    }

    /**
     * Create an instance of {@link SelNumType }
     * 
     */
    public SelNumType createSelNumType() {
        return new SelNumType();
    }

    /**
     * Create an instance of {@link IdrefType }
     * 
     */
    public IdrefType createIdrefType() {
        return new IdrefType();
    }

    /**
     * Create an instance of {@link BenchmarkReferenceType }
     * 
     */
    public BenchmarkReferenceType createBenchmarkReferenceType() {
        return new BenchmarkReferenceType();
    }

    /**
     * Create an instance of {@link TargetIdRefType }
     * 
     */
    public TargetIdRefType createTargetIdRefType() {
        return new TargetIdRefType();
    }

    /**
     * Create an instance of {@link FixTextType }
     * 
     */
    public FixTextType createFixTextType() {
        return new FixTextType();
    }

    /**
     * Create an instance of {@link ProfileSetComplexValueType }
     * 
     */
    public ProfileSetComplexValueType createProfileSetComplexValueType() {
        return new ProfileSetComplexValueType();
    }

    /**
     * Create an instance of {@link TailoringVersionType }
     * 
     */
    public TailoringVersionType createTailoringVersionType() {
        return new TailoringVersionType();
    }

    /**
     * Create an instance of {@link IdrefListType }
     * 
     */
    public IdrefListType createIdrefListType() {
        return new IdrefListType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Item")
    public JAXBElement<ItemType> createItem(ItemType value) {
        return new JAXBElement<ItemType>(_Item_QNAME, ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Group")
    public JAXBElement<GroupType> createGroup(GroupType value) {
        return new JAXBElement<GroupType>(_Group_QNAME, GroupType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Value")
    public JAXBElement<ValueType> createValue(ValueType value) {
        return new JAXBElement<ValueType>(_Value_QNAME, ValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestResultType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "TestResult")
    public JAXBElement<TestResultType> createTestResult(TestResultType value) {
        return new JAXBElement<TestResultType>(_TestResult_QNAME, TestResultType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RuleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Rule")
    public JAXBElement<RuleType> createRule(RuleType value) {
        return new JAXBElement<RuleType>(_Rule_QNAME, RuleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProfileType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Profile")
    public JAXBElement<ProfileType> createProfile(ProfileType value) {
        return new JAXBElement<ProfileType>(_Profile_QNAME, ProfileType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TailoringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "Tailoring")
    public JAXBElement<TailoringType> createTailoring(TailoringType value) {
        return new JAXBElement<TailoringType>(_Tailoring_QNAME, TailoringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "sub", scope = ProfileNoteType.class)
    public JAXBElement<SubType> createProfileNoteTypeSub(SubType value) {
        return new JAXBElement<SubType>(_ProfileNoteTypeSub_QNAME, SubType.class, ProfileNoteType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "sub", scope = TextWithSubType.class)
    public JAXBElement<SubType> createTextWithSubTypeSub(SubType value) {
        return new JAXBElement<SubType>(_ProfileNoteTypeSub_QNAME, SubType.class, TextWithSubType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TargetIdRefType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "target-id-ref", scope = TestResultType.class)
    public JAXBElement<TargetIdRefType> createTestResultTypeTargetIdRef(TargetIdRefType value) {
        return new JAXBElement<TargetIdRefType>(_TestResultTypeTargetIdRef_QNAME, TargetIdRefType.class, TestResultType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "sub", scope = FixType.class)
    public JAXBElement<SubType> createFixTypeSub(SubType value) {
        return new JAXBElement<SubType>(_ProfileNoteTypeSub_QNAME, SubType.class, FixType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InstanceFixType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "instance", scope = FixType.class)
    public JAXBElement<InstanceFixType> createFixTypeInstance(InstanceFixType value) {
        return new JAXBElement<InstanceFixType>(_FixTypeInstance_QNAME, InstanceFixType.class, FixType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://checklists.nist.gov/xccdf/1.2", name = "sub", scope = HtmlTextWithSubType.class)
    public JAXBElement<SubType> createHtmlTextWithSubTypeSub(SubType value) {
        return new JAXBElement<SubType>(_ProfileNoteTypeSub_QNAME, SubType.class, HtmlTextWithSubType.class, value);
    }

}
