//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://checklists.nist.gov/xccdf/1.2", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package xccdfClasses;
