//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:Profile> element, which
 *                 holds a specific tailoring of the <xccdf:Benchmark>. The main part of an
 *                 <xccdf:Profile> is the selectors: <xccdf:select>,
 *                 <xccdf:set-value>, <xccdf:set-complex-value>, <xccdf:refine-rule>,
 *                 and <xccdf:refine-value>. An <xccdf:Profile> may also be signed with an
 *                 XML-Signature. 
 * 
 * <p>Java class for profileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="profileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://checklists.nist.gov/xccdf/1.2}status" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dc-status" type="{http://checklists.nist.gov/xccdf/1.2}dc-statusType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="version" type="{http://checklists.nist.gov/xccdf/1.2}versionType" minOccurs="0"/>
 *         &lt;element name="title" type="{http://checklists.nist.gov/xccdf/1.2}textWithSubType" maxOccurs="unbounded"/>
 *         &lt;element name="description" type="{http://checklists.nist.gov/xccdf/1.2}htmlTextWithSubType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="reference" type="{http://checklists.nist.gov/xccdf/1.2}referenceType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="platform" type="{http://checklists.nist.gov/xccdf/1.2}overrideableCPE2idrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="select" type="{http://checklists.nist.gov/xccdf/1.2}profileSelectType" minOccurs="0"/>
 *           &lt;element name="set-complex-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetComplexValueType" minOccurs="0"/>
 *           &lt;element name="set-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetValueType" minOccurs="0"/>
 *           &lt;element name="refine-value" type="{http://checklists.nist.gov/xccdf/1.2}profileRefineValueType" minOccurs="0"/>
 *           &lt;element name="refine-rule" type="{http://checklists.nist.gov/xccdf/1.2}profileRefineRuleType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="metadata" type="{http://checklists.nist.gov/xccdf/1.2}metadataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}profileIdType" />
 *       &lt;attribute name="prohibitChanges" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="abstract" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="note-tag" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *       &lt;attribute name="extends" type="{http://www.w3.org/2001/XMLSchema}NCName" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "profileType", propOrder = {
    "status",
    "dcStatus",
    "version",
    "title",
    "description",
    "reference",
    "platform",
    "selectOrSetComplexValueOrSetValue",
    "metadata",
    "signature"
})
public class ProfileType {

    protected List<Status> status;
    @XmlElement(name = "dc-status")
    protected List<DcStatusType> dcStatus;
    protected VersionType version;
    @XmlElement(required = true)
    protected List<TextWithSubType> title;
    protected List<HtmlTextWithSubType> description;
    protected List<ReferenceType> reference;
    protected List<OverrideableCPE2IdrefType> platform;
    @XmlElements({
        @XmlElement(name = "select", type = ProfileSelectType.class),
        @XmlElement(name = "set-complex-value", type = ProfileSetComplexValueType.class),
        @XmlElement(name = "set-value", type = ProfileSetValueType.class),
        @XmlElement(name = "refine-value", type = ProfileRefineValueType.class),
        @XmlElement(name = "refine-rule", type = ProfileRefineRuleType.class)
    })
    protected List<Object> selectOrSetComplexValueOrSetValue;
    protected List<MetadataType> metadata;
    protected SignatureType signature;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "prohibitChanges")
    protected Boolean prohibitChanges;
    @XmlAttribute(name = "abstract")
    protected Boolean _abstract;
    @XmlAttribute(name = "note-tag")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String noteTag;
    @XmlAttribute(name = "extends")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String _extends;

    /**
     * Status of the <xccdf:Profile> and date at
     *                         which it attained that status. Authors may use this element to record the
     *                         maturity or consensus level of an <xccdf:Profile>. If the
     *                         <xccdf:status> is not given explicitly, then the <xccdf:Profile>
     *                         is taken to have the same status as its parent
     *                         <xccdf:Benchmark>.Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Status }
     * 
     * 
     */
    public List<Status> getStatus() {
        if (status == null) {
            status = new ArrayList<Status>();
        }
        return this.status;
    }

    /**
     * Gets the value of the dcStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcStatusType }
     * 
     * 
     */
    public List<DcStatusType> getDcStatus() {
        if (dcStatus == null) {
            dcStatus = new ArrayList<DcStatusType>();
        }
        return this.dcStatus;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link VersionType }
     *     
     */
    public VersionType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionType }
     *     
     */
    public void setVersion(VersionType value) {
        this.version = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextWithSubType }
     * 
     * 
     */
    public List<TextWithSubType> getTitle() {
        if (title == null) {
            title = new ArrayList<TextWithSubType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HtmlTextWithSubType }
     * 
     * 
     */
    public List<HtmlTextWithSubType> getDescription() {
        if (description == null) {
            description = new ArrayList<HtmlTextWithSubType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the reference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReferenceType }
     * 
     * 
     */
    public List<ReferenceType> getReference() {
        if (reference == null) {
            reference = new ArrayList<ReferenceType>();
        }
        return this.reference;
    }

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OverrideableCPE2IdrefType }
     * 
     * 
     */
    public List<OverrideableCPE2IdrefType> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<OverrideableCPE2IdrefType>();
        }
        return this.platform;
    }

    /**
     * Gets the value of the selectOrSetComplexValueOrSetValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectOrSetComplexValueOrSetValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectOrSetComplexValueOrSetValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileSelectType }
     * {@link ProfileSetComplexValueType }
     * {@link ProfileSetValueType }
     * {@link ProfileRefineValueType }
     * {@link ProfileRefineRuleType }
     * 
     * 
     */
    public List<Object> getSelectOrSetComplexValueOrSetValue() {
        if (selectOrSetComplexValueOrSetValue == null) {
            selectOrSetComplexValueOrSetValue = new ArrayList<Object>();
        }
        return this.selectOrSetComplexValueOrSetValue;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataType }
     * 
     * 
     */
    public List<MetadataType> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<MetadataType>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the prohibitChanges property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isProhibitChanges() {
        if (prohibitChanges == null) {
            return false;
        } else {
            return prohibitChanges;
        }
    }

    /**
     * Sets the value of the prohibitChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setProhibitChanges(Boolean value) {
        this.prohibitChanges = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isAbstract() {
        if (_abstract == null) {
            return false;
        } else {
            return _abstract;
        }
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAbstract(Boolean value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the noteTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteTag() {
        return noteTag;
    }

    /**
     * Sets the value of the noteTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteTag(String value) {
        this.noteTag = value;
    }

    /**
     * Gets the value of the extends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtends() {
        return _extends;
    }

    /**
     * Sets the value of the extends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtends(String value) {
        this._extends = value;
    }

}
