//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for resultEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="resultEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="pass"/>
 *     &lt;enumeration value="fail"/>
 *     &lt;enumeration value="error"/>
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="notapplicable"/>
 *     &lt;enumeration value="notchecked"/>
 *     &lt;enumeration value="notselected"/>
 *     &lt;enumeration value="informational"/>
 *     &lt;enumeration value="fixed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "resultEnumType")
@XmlEnum
public enum ResultEnumType {


    /**
     * The target system or system component satisfied
     *                         all the conditions of the <xccdf:Rule>. 
     * 
     */
    @XmlEnumValue("pass")
    PASS("pass"),

    /**
     * The target system or system component did not
     *                         satisfy all the conditions of the <xccdf:Rule>. 
     * 
     */
    @XmlEnumValue("fail")
    FAIL("fail"),

    /**
     * The checking engine could not complete the
     *                         evaluation; therefore the status of the target’s compliance with the
     *                         <xccdf:Rule> is not certain. This could happen, for example, if a
     *                         testing tool was run with insufficient privileges and could not gather all
     *                         of the necessary information. 
     * 
     */
    @XmlEnumValue("error")
    ERROR("error"),

    /**
     * The testing tool encountered some problem and
     *                         the result is unknown. For example, a result of ‘unknown’ might be given if
     *                         the testing tool was unable to interpret the output of the checking engine
     *                         (the output has no meaning to the testing tool). 
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),

    /**
     * The <xccdf:Rule> was not applicable to
     *                         the target of the test. For example, the <xccdf:Rule> might have been
     *                         specific to a different version of the target OS, or it might have been a
     *                         test against a platform feature that was not installed. 
     * 
     */
    @XmlEnumValue("notapplicable")
    NOTAPPLICABLE("notapplicable"),

    /**
     * The <xccdf:Rule> was not evaluated by the
     *                         checking engine. This status is designed for <xccdf:Rule> elements
     *                         that have no check. It may also correspond to a status returned by a
     *                         checking engine if the checking engine does not support the indicated check
     *                         code. 
     * 
     */
    @XmlEnumValue("notchecked")
    NOTCHECKED("notchecked"),

    /**
     * The <xccdf:Rule> was not selected in the
     *                         <xccdf:Benchmark>. 
     * 
     */
    @XmlEnumValue("notselected")
    NOTSELECTED("notselected"),

    /**
     * The <xccdf:Rule> was checked, but the
     *                         output from the checking engine is simply information for auditors or
     *                         administrators; it is not a compliance category. This status value is
     *                         designed for <xccdf:Rule> elements whose main purpose is to extract
     *                         information from the target rather than test the target.
     *                     
     * 
     */
    @XmlEnumValue("informational")
    INFORMATIONAL("informational"),

    /**
     * The <xccdf:Rule> had failed, but was then
     *                         fixed (possibly by a tool that can automatically apply remediation, or
     *                         possibly by the human auditor). 
     * 
     */
    @XmlEnumValue("fixed")
    FIXED("fixed");
    private final String value;

    ResultEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResultEnumType fromValue(String v) {
        for (ResultEnumType c: ResultEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
