//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:Rule> element that
 *                 represents a specific <xccdf:Benchmark> test. 
 * 
 * <p>Java class for ruleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruleType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://checklists.nist.gov/xccdf/1.2}selectableItemType">
 *       &lt;sequence>
 *         &lt;element name="ident" type="{http://checklists.nist.gov/xccdf/1.2}identType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="impact-metric" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="profile-note" type="{http://checklists.nist.gov/xccdf/1.2}profileNoteType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fixtext" type="{http://checklists.nist.gov/xccdf/1.2}fixTextType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fix" type="{http://checklists.nist.gov/xccdf/1.2}fixType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="check" type="{http://checklists.nist.gov/xccdf/1.2}checkType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="complex-check" type="{http://checklists.nist.gov/xccdf/1.2}complexCheckType" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}ruleIdType" />
 *       &lt;attribute name="role" type="{http://checklists.nist.gov/xccdf/1.2}roleEnumType" default="full" />
 *       &lt;attribute name="severity" type="{http://checklists.nist.gov/xccdf/1.2}severityEnumType" default="unknown" />
 *       &lt;attribute name="multiple" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleType", propOrder = {
    "ident",
    "impactMetric",
    "profileNote",
    "fixtext",
    "fix",
    "check",
    "complexCheck",
    "signature"
})
public class RuleType
    extends SelectableItemType
{

    protected List<IdentType> ident;
    @XmlElement(name = "impact-metric")
    protected String impactMetric;
    @XmlElement(name = "profile-note")
    protected List<ProfileNoteType> profileNote;
    protected List<FixTextType> fixtext;
    protected List<FixType> fix;
    protected List<CheckType> check;
    @XmlElement(name = "complex-check")
    protected ComplexCheckType complexCheck;
    protected SignatureType signature;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "role")
    protected RoleEnumType role;
    @XmlAttribute(name = "severity")
    protected SeverityEnumType severity;
    @XmlAttribute(name = "multiple")
    protected Boolean multiple;

    /**
     * Gets the value of the ident property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ident property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIdent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentType }
     * 
     * 
     */
    public List<IdentType> getIdent() {
        if (ident == null) {
            ident = new ArrayList<IdentType>();
        }
        return this.ident;
    }

    /**
     * Gets the value of the impactMetric property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpactMetric() {
        return impactMetric;
    }

    /**
     * Sets the value of the impactMetric property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpactMetric(String value) {
        this.impactMetric = value;
    }

    /**
     * Gets the value of the profileNote property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profileNote property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfileNote().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileNoteType }
     * 
     * 
     */
    public List<ProfileNoteType> getProfileNote() {
        if (profileNote == null) {
            profileNote = new ArrayList<ProfileNoteType>();
        }
        return this.profileNote;
    }

    /**
     * Gets the value of the fixtext property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fixtext property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFixtext().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FixTextType }
     * 
     * 
     */
    public List<FixTextType> getFixtext() {
        if (fixtext == null) {
            fixtext = new ArrayList<FixTextType>();
        }
        return this.fixtext;
    }

    /**
     * Gets the value of the fix property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fix property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFix().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FixType }
     * 
     * 
     */
    public List<FixType> getFix() {
        if (fix == null) {
            fix = new ArrayList<FixType>();
        }
        return this.fix;
    }

    /**
     * Gets the value of the check property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the check property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCheck().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CheckType }
     * 
     * 
     */
    public List<CheckType> getCheck() {
        if (check == null) {
            check = new ArrayList<CheckType>();
        }
        return this.check;
    }

    /**
     * Gets the value of the complexCheck property.
     * 
     * @return
     *     possible object is
     *     {@link ComplexCheckType }
     *     
     */
    public ComplexCheckType getComplexCheck() {
        return complexCheck;
    }

    /**
     * Sets the value of the complexCheck property.
     * 
     * @param value
     *     allowed object is
     *     {@link ComplexCheckType }
     *     
     */
    public void setComplexCheck(ComplexCheckType value) {
        this.complexCheck = value;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the role property.
     * 
     * @return
     *     possible object is
     *     {@link RoleEnumType }
     *     
     */
    public RoleEnumType getRole() {
        if (role == null) {
            return RoleEnumType.FULL;
        } else {
            return role;
        }
    }

    /**
     * Sets the value of the role property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoleEnumType }
     *     
     */
    public void setRole(RoleEnumType value) {
        this.role = value;
    }

    /**
     * Gets the value of the severity property.
     * 
     * @return
     *     possible object is
     *     {@link SeverityEnumType }
     *     
     */
    public SeverityEnumType getSeverity() {
        if (severity == null) {
            return SeverityEnumType.UNKNOWN;
        } else {
            return severity;
        }
    }

    /**
     * Sets the value of the severity property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeverityEnumType }
     *     
     */
    public void setSeverity(SeverityEnumType value) {
        this.severity = value;
    }

    /**
     * Gets the value of the multiple property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMultiple() {
        if (multiple == null) {
            return false;
        } else {
            return multiple;
        }
    }

    /**
     * Sets the value of the multiple property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMultiple(Boolean value) {
        this.multiple = value;
    }

}
