//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * The type used for <xccdf:sub> elements. The
 *                 <xccdf:sub> element identifies replacement content that should appear in place
 *                 of the <xccdf:sub> element during text substitution. The subType consists of a
 *                 regular idrefType with an additional @use attribute to dictate the behavior of the
 *                 <xccdf:sub> element under substitution. When the @idref is to an
 *                 <xccdf:Value>, the @use attribute indicates whether the <xccdf:Value>
 *                 element's title or value should replace the <xccdf:sub> element. The @use
 *                 attribute is ignored when the @idref is to an <xccdf:plain-text> element; the
 *                 body of the <xccdf:plain-text> element is always used to replace the
 *                 <xccdf:sub> element.
 * 
 * <p>Java class for subType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://checklists.nist.gov/xccdf/1.2}idrefType">
 *       &lt;attribute name="use" type="{http://checklists.nist.gov/xccdf/1.2}subUseEnumType" default="value" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subType")
public class SubType
    extends IdrefType
{

    @XmlAttribute(name = "use")
    protected SubUseEnumType use;

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link SubUseEnumType }
     *     
     */
    public SubUseEnumType getUse() {
        if (use == null) {
            return SubUseEnumType.VALUE;
        } else {
            return use;
        }
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubUseEnumType }
     *     
     */
    public void setUse(SubUseEnumType value) {
        this.use = value;
    }

}
