//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Data type for the <xccdf:Tailoring> element. The
 *                 <xccdf:Tailoring> element allows named tailorings (i.e., <xccdf:Profile>
 *                 elements) of an <xccdf:Benchmark> to be defined separately from the
 *                 <xccdf:Benchmark> itself. The <xccdf:Profile> elements in an
 *                 <xccdf:Tailoring> element can be used in two ways: First, an organization
 *                 might wish to pre-define a set of tailoring actions to be applied on top of or
 *                 instead of the tailoring performed by an <xccdf:Benchmark> element's
 *                 <xccdf:Profile> elements. Second, an <xccdf:Tailoring> element can be
 *                 used to record manual tailoring actions performed during the course of an
 *                 assessment. 
 * 
 * <p>Java class for tailoringType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tailoringType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="benchmark" type="{http://checklists.nist.gov/xccdf/1.2}tailoringBenchmarkReferenceType" minOccurs="0"/>
 *         &lt;element ref="{http://checklists.nist.gov/xccdf/1.2}status" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="dc-status" type="{http://checklists.nist.gov/xccdf/1.2}dc-statusType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="version" type="{http://checklists.nist.gov/xccdf/1.2}tailoringVersionType"/>
 *         &lt;element name="metadata" type="{http://checklists.nist.gov/xccdf/1.2}metadataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://checklists.nist.gov/xccdf/1.2}Profile" maxOccurs="unbounded"/>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}tailoringIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tailoringType", propOrder = {
    "benchmark",
    "status",
    "dcStatus",
    "version",
    "metadata",
    "profile",
    "signature"
})
public class TailoringType {

    protected TailoringBenchmarkReferenceType benchmark;
    protected List<Status> status;
    @XmlElement(name = "dc-status")
    protected List<DcStatusType> dcStatus;
    @XmlElement(required = true)
    protected TailoringVersionType version;
    protected List<MetadataType> metadata;
    @XmlElement(name = "Profile", required = true)
    protected List<ProfileType> profile;
    protected SignatureType signature;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the benchmark property.
     * 
     * @return
     *     possible object is
     *     {@link TailoringBenchmarkReferenceType }
     *     
     */
    public TailoringBenchmarkReferenceType getBenchmark() {
        return benchmark;
    }

    /**
     * Sets the value of the benchmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link TailoringBenchmarkReferenceType }
     *     
     */
    public void setBenchmark(TailoringBenchmarkReferenceType value) {
        this.benchmark = value;
    }

    /**
     * Status of the tailoring and date at which it
     *                         attained that status. Authors may use this element to record the maturity or
     *                         consensus level of an <xccdf:Tailoring> element.Gets the value of the status property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the status property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Status }
     * 
     * 
     */
    public List<Status> getStatus() {
        if (status == null) {
            status = new ArrayList<Status>();
        }
        return this.status;
    }

    /**
     * Gets the value of the dcStatus property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dcStatus property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDcStatus().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DcStatusType }
     * 
     * 
     */
    public List<DcStatusType> getDcStatus() {
        if (dcStatus == null) {
            dcStatus = new ArrayList<DcStatusType>();
        }
        return this.dcStatus;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link TailoringVersionType }
     *     
     */
    public TailoringVersionType getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link TailoringVersionType }
     *     
     */
    public void setVersion(TailoringVersionType value) {
        this.version = value;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataType }
     * 
     * 
     */
    public List<MetadataType> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<MetadataType>();
        }
        return this.metadata;
    }

    /**
     * <xccdf:Profile> elements that reference
     *                         and customize sets of items in an <xccdf:Benchmark>.
     *                     Gets the value of the profile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileType }
     * 
     * 
     */
    public List<ProfileType> getProfile() {
        if (profile == null) {
            profile = new ArrayList<ProfileType>();
        }
        return this.profile;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
