//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 *  Data type for the <xccdf:target-facts> elements
 *                 in <xccdf:TestResult> elements. A <xccdf:target-facts> element holds a
 *                 list of named facts about the target system or platform. Each fact is an element of
 *                 type factType. Each <xccdf:fact> must have a name, but duplicate names are
 *                 allowed. (For example, if you had a fact about MAC addresses, and the target system
 *                 had three NICs, then you'd need three instances of the "urn:xccdf:fact:ethernet:MAC"
 *                 fact.) 
 * 
 * <p>Java class for targetFactsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="targetFactsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fact" type="{http://checklists.nist.gov/xccdf/1.2}factType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "targetFactsType", propOrder = {
    "fact"
})
public class TargetFactsType {

    protected List<FactType> fact;

    /**
     * Gets the value of the fact property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fact property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFact().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FactType }
     * 
     * 
     */
    public List<FactType> getFact() {
        if (fact == null) {
            fact = new ArrayList<FactType>();
        }
        return this.fact;
    }

}
