//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfClasses;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.w3c.dom.Element;


/**
 *  Data type for the <xccdf:TestResult> element,
 *                 which holds the results of one application of the <xccdf:Benchmark>. The
 *                 <xccdf:TestResult> element normally appears as the child of the
 *                 <xccdf:Benchmark> element, although it may also appear as the top-level
 *                 element of an XCCDF results document. XCCDF is not intended to be a database format
 *                 for detailed results; the <xccdf:TestResult> element offers a way to store the
 *                 results of individual tests in modest detail, with the ability to reference
 *                 lower-level testing data. Although several of the child elements of this type
 *                 technically support the @override attribute, the <xccdf:TestResult> element
 *                 cannot be extended. Therefore, @override has no meaning within an
 *                 <xccdf:TestResult> element and its children, and should not be used for
 *                 them.
 * 
 * <p>Java class for testResultType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="testResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="benchmark" type="{http://checklists.nist.gov/xccdf/1.2}benchmarkReferenceType" minOccurs="0"/>
 *         &lt;element name="tailoring-file" type="{http://checklists.nist.gov/xccdf/1.2}tailoringReferenceType" minOccurs="0"/>
 *         &lt;element name="title" type="{http://checklists.nist.gov/xccdf/1.2}textType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="remark" type="{http://checklists.nist.gov/xccdf/1.2}textType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="organization" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="identity" type="{http://checklists.nist.gov/xccdf/1.2}identityType" minOccurs="0"/>
 *         &lt;element name="profile" type="{http://checklists.nist.gov/xccdf/1.2}idrefType" minOccurs="0"/>
 *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *         &lt;element name="target-address" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="target-facts" type="{http://checklists.nist.gov/xccdf/1.2}targetFactsType" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="target-id-ref" type="{http://checklists.nist.gov/xccdf/1.2}targetIdRefType"/>
 *           &lt;any processContents='lax' namespace='##other'/>
 *         &lt;/choice>
 *         &lt;element name="platform" type="{http://checklists.nist.gov/xccdf/1.2}CPE2idrefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="set-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetValueType"/>
 *           &lt;element name="set-complex-value" type="{http://checklists.nist.gov/xccdf/1.2}profileSetComplexValueType"/>
 *         &lt;/choice>
 *         &lt;element name="rule-result" type="{http://checklists.nist.gov/xccdf/1.2}ruleResultType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="score" type="{http://checklists.nist.gov/xccdf/1.2}scoreType" maxOccurs="unbounded"/>
 *         &lt;element name="metadata" type="{http://checklists.nist.gov/xccdf/1.2}metadataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}testresultIdType" />
 *       &lt;attribute name="start-time" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="end-time" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="test-system" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "testResultType", propOrder = {
    "benchmark",
    "tailoringFile",
    "title",
    "remark",
    "organization",
    "identity",
    "profile",
    "target",
    "targetAddress",
    "targetFacts",
    "targetIdRefOrAny",
    "platform",
    "setValueOrSetComplexValue",
    "ruleResult",
    "score",
    "metadata",
    "signature"
})
public class TestResultType {

    protected BenchmarkReferenceType benchmark;
    @XmlElement(name = "tailoring-file")
    protected TailoringReferenceType tailoringFile;
    protected List<TextType> title;
    protected List<TextType> remark;
    protected List<String> organization;
    protected IdentityType identity;
    protected IdrefType profile;
    @XmlElement(required = true)
    protected List<String> target;
    @XmlElement(name = "target-address")
    protected List<String> targetAddress;
    @XmlElement(name = "target-facts")
    protected TargetFactsType targetFacts;
    @XmlElementRef(name = "target-id-ref", namespace = "http://checklists.nist.gov/xccdf/1.2", type = JAXBElement.class, required = false)
    @XmlAnyElement(lax = true)
    protected List<Object> targetIdRefOrAny;
    protected List<CPE2IdrefType> platform;
    @XmlElements({
        @XmlElement(name = "set-value", type = ProfileSetValueType.class),
        @XmlElement(name = "set-complex-value", type = ProfileSetComplexValueType.class)
    })
    protected List<Object> setValueOrSetComplexValue;
    @XmlElement(name = "rule-result")
    protected List<RuleResultType> ruleResult;
    @XmlElement(required = true)
    protected List<ScoreType> score;
    protected List<MetadataType> metadata;
    protected SignatureType signature;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "start-time")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar startTime;
    @XmlAttribute(name = "end-time", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar endTime;
    @XmlAttribute(name = "test-system")
    protected String testSystem;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the benchmark property.
     * 
     * @return
     *     possible object is
     *     {@link BenchmarkReferenceType }
     *     
     */
    public BenchmarkReferenceType getBenchmark() {
        return benchmark;
    }

    /**
     * Sets the value of the benchmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link BenchmarkReferenceType }
     *     
     */
    public void setBenchmark(BenchmarkReferenceType value) {
        this.benchmark = value;
    }

    /**
     * Gets the value of the tailoringFile property.
     * 
     * @return
     *     possible object is
     *     {@link TailoringReferenceType }
     *     
     */
    public TailoringReferenceType getTailoringFile() {
        return tailoringFile;
    }

    /**
     * Sets the value of the tailoringFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TailoringReferenceType }
     *     
     */
    public void setTailoringFile(TailoringReferenceType value) {
        this.tailoringFile = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the title property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTitle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getTitle() {
        if (title == null) {
            title = new ArrayList<TextType>();
        }
        return this.title;
    }

    /**
     * Gets the value of the remark property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remark property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemark().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getRemark() {
        if (remark == null) {
            remark = new ArrayList<TextType>();
        }
        return this.remark;
    }

    /**
     * Gets the value of the organization property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the organization property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrganization().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOrganization() {
        if (organization == null) {
            organization = new ArrayList<String>();
        }
        return this.organization;
    }

    /**
     * Gets the value of the identity property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType }
     *     
     */
    public IdentityType getIdentity() {
        return identity;
    }

    /**
     * Sets the value of the identity property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType }
     *     
     */
    public void setIdentity(IdentityType value) {
        this.identity = value;
    }

    /**
     * Gets the value of the profile property.
     * 
     * @return
     *     possible object is
     *     {@link IdrefType }
     *     
     */
    public IdrefType getProfile() {
        return profile;
    }

    /**
     * Sets the value of the profile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdrefType }
     *     
     */
    public void setProfile(IdrefType value) {
        this.profile = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTarget() {
        if (target == null) {
            target = new ArrayList<String>();
        }
        return this.target;
    }

    /**
     * Gets the value of the targetAddress property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetAddress property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetAddress().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTargetAddress() {
        if (targetAddress == null) {
            targetAddress = new ArrayList<String>();
        }
        return this.targetAddress;
    }

    /**
     * Gets the value of the targetFacts property.
     * 
     * @return
     *     possible object is
     *     {@link TargetFactsType }
     *     
     */
    public TargetFactsType getTargetFacts() {
        return targetFacts;
    }

    /**
     * Sets the value of the targetFacts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetFactsType }
     *     
     */
    public void setTargetFacts(TargetFactsType value) {
        this.targetFacts = value;
    }

    /**
     * Gets the value of the targetIdRefOrAny property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetIdRefOrAny property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetIdRefOrAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link TargetIdRefType }{@code >}
     * {@link Object }
     * 
     * 
     */
    public List<Object> getTargetIdRefOrAny() {
        if (targetIdRefOrAny == null) {
            targetIdRefOrAny = new ArrayList<Object>();
        }
        return this.targetIdRefOrAny;
    }

    /**
     * Gets the value of the platform property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the platform property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlatform().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CPE2IdrefType }
     * 
     * 
     */
    public List<CPE2IdrefType> getPlatform() {
        if (platform == null) {
            platform = new ArrayList<CPE2IdrefType>();
        }
        return this.platform;
    }

    /**
     * Gets the value of the setValueOrSetComplexValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setValueOrSetComplexValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetValueOrSetComplexValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileSetValueType }
     * {@link ProfileSetComplexValueType }
     * 
     * 
     */
    public List<Object> getSetValueOrSetComplexValue() {
        if (setValueOrSetComplexValue == null) {
            setValueOrSetComplexValue = new ArrayList<Object>();
        }
        return this.setValueOrSetComplexValue;
    }

    /**
     * Gets the value of the ruleResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ruleResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRuleResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RuleResultType }
     * 
     * 
     */
    public List<RuleResultType> getRuleResult() {
        if (ruleResult == null) {
            ruleResult = new ArrayList<RuleResultType>();
        }
        return this.ruleResult;
    }

    /**
     * Gets the value of the score property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the score property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getScore().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ScoreType }
     * 
     * 
     */
    public List<ScoreType> getScore() {
        if (score == null) {
            score = new ArrayList<ScoreType>();
        }
        return this.score;
    }

    /**
     * Gets the value of the metadata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadata().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MetadataType }
     * 
     * 
     */
    public List<MetadataType> getMetadata() {
        if (metadata == null) {
            metadata = new ArrayList<MetadataType>();
        }
        return this.metadata;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the startTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartTime() {
        return startTime;
    }

    /**
     * Sets the value of the startTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartTime(XMLGregorianCalendar value) {
        this.startTime = value;
    }

    /**
     * Gets the value of the endTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndTime() {
        return endTime;
    }

    /**
     * Sets the value of the endTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndTime(XMLGregorianCalendar value) {
        this.endTime = value;
    }

    /**
     * Gets the value of the testSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTestSystem() {
        return testSystem;
    }

    /**
     * Sets the value of the testSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTestSystem(String value) {
        this.testSystem = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
