//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.02 at 06:54:38 PM CDT 
//


package checklist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}VULN_ATTRIBUTE"/>
 *         &lt;element ref="{}ATTRIBUTE_DATA"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vulnattribute",
    "attributedata"
})
@XmlRootElement(name = "STIG_DATA")
public class STIGDATA {

    @XmlElement(name = "VULN_ATTRIBUTE", required = true)
    protected String vulnattribute;
    @XmlElement(name = "ATTRIBUTE_DATA", required = true)
    protected String attributedata;

    /**
     * Gets the value of the vulnattribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVULNATTRIBUTE() {
        return vulnattribute;
    }

    /**
     * Sets the value of the vulnattribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVULNATTRIBUTE(String value) {
        this.vulnattribute = value;
    }

    /**
     * Gets the value of the attributedata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATTRIBUTEDATA() {
        return attributedata;
    }

    /**
     * Sets the value of the attributedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATTRIBUTEDATA(String value) {
        this.attributedata = value;
    }

}
