//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.02 at 06:54:38 PM CDT 
//


package checklist;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}STIG_DATA" maxOccurs="unbounded"/>
 *         &lt;element ref="{}STATUS"/>
 *         &lt;element ref="{}FINDING_DETAILS"/>
 *         &lt;element ref="{}COMMENTS"/>
 *         &lt;element ref="{}SEVERITY_OVERRIDE"/>
 *         &lt;element ref="{}SEVERITY_JUSTIFICATION"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stigdata",
    "status",
    "findingdetails",
    "comments",
    "severityoverride",
    "severityjustification"
})
@XmlRootElement(name = "VULN")
public class VULN {

    @XmlElement(name = "STIG_DATA", required = true)
    protected List<STIGDATA> stigdata;
    @XmlElement(name = "STATUS", required = true)
    protected String status;
    @XmlElement(name = "FINDING_DETAILS", required = true)
    protected String findingdetails;
    @XmlElement(name = "COMMENTS", required = true)
    protected String comments;
    @XmlElement(name = "SEVERITY_OVERRIDE", required = true)
    protected String severityoverride;
    @XmlElement(name = "SEVERITY_JUSTIFICATION", required = true)
    protected String severityjustification;

    /**
     * Gets the value of the stigdata property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stigdata property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSTIGDATA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link STIGDATA }
     * 
     * 
     */
    public List<STIGDATA> getSTIGDATA() {
        if (stigdata == null) {
            stigdata = new ArrayList<STIGDATA>();
        }
        return this.stigdata;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTATUS() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTATUS(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the findingdetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFINDINGDETAILS() {
        return findingdetails;
    }

    /**
     * Sets the value of the findingdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFINDINGDETAILS(String value) {
        this.findingdetails = value;
    }

    /**
     * Gets the value of the comments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMMENTS() {
        return comments;
    }

    /**
     * Sets the value of the comments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMMENTS(String value) {
        this.comments = value;
    }

    /**
     * Gets the value of the severityoverride property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEVERITYOVERRIDE() {
        return severityoverride;
    }

    /**
     * Sets the value of the severityoverride property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEVERITYOVERRIDE(String value) {
        this.severityoverride = value;
    }

    /**
     * Gets the value of the severityjustification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEVERITYJUSTIFICATION() {
        return severityjustification;
    }

    /**
     * Sets the value of the severityjustification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEVERITYJUSTIFICATION(String value) {
        this.severityjustification = value;
    }

}
