//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package junk;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 *  Data type for the <xccdf:check-import> element,
 *                 which specifies a value that the <xccdf:Benchmark> author wishes to retrieve
 *                 from the checking system during testing of a target system. The @import-name
 *                 attribute identifies some structure in the checking system that is then retrieved.
 *                 The mapping from the values of this attribute to specific checking system structures
 *                 is beyond the scope of the XCCDF specification. When the <xccdf:check-import>
 *                 element appears in the context of an <xccdf:Rule>, then it should be empty and
 *                 any content must be ignored. When the <xccdf:check-import> element appears in
 *                 the context of an <xccdf:rule-result>, then its body holds the imported value.
 *             
 * 
 * <p>Java class for checkImportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="checkImportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;any processContents='skip' minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="import-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="import-xpath" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "checkImportType", propOrder = {
    "content"
})
public class CheckImportType {

    @XmlMixed
    @XmlAnyElement
    protected List<Object> content;
    @XmlAttribute(name = "import-name", required = true)
    protected String importName;
    @XmlAttribute(name = "import-xpath")
    protected String importXpath;

    /**
     *  Data type for the <xccdf:check-import> element,
     *                 which specifies a value that the <xccdf:Benchmark> author wishes to retrieve
     *                 from the checking system during testing of a target system. The @import-name
     *                 attribute identifies some structure in the checking system that is then retrieved.
     *                 The mapping from the values of this attribute to specific checking system structures
     *                 is beyond the scope of the XCCDF specification. When the <xccdf:check-import>
     *                 element appears in the context of an <xccdf:Rule>, then it should be empty and
     *                 any content must be ignored. When the <xccdf:check-import> element appears in
     *                 the context of an <xccdf:rule-result>, then its body holds the imported value.
     *             Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Element }
     * {@link String }
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the importName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportName() {
        return importName;
    }

    /**
     * Sets the value of the importName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportName(String value) {
        this.importName = value;
    }

    /**
     * Gets the value of the importXpath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportXpath() {
        return importXpath;
    }

    /**
     * Sets the value of the importXpath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportXpath(String value) {
        this.importXpath = value;
    }

}
