//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package junk;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ratingEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ratingEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="unknown"/>
 *     &lt;enumeration value="low"/>
 *     &lt;enumeration value="medium"/>
 *     &lt;enumeration value="high"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ratingEnumType")
@XmlEnum
public enum RatingEnumType {


    /**
     * Rating unknown or impossible to estimate
     *                         (default)
     * 
     */
    @XmlEnumValue("unknown")
    UNKNOWN("unknown"),

    /**
     * Little or no potential for disruption, very
     *                         modest complexity
     * 
     */
    @XmlEnumValue("low")
    LOW("low"),

    /**
     * Some chance of minor disruption, substantial
     *                         complexity
     * 
     */
    @XmlEnumValue("medium")
    MEDIUM("medium"),

    /**
     * Likely to cause serious disruption, very
     *                         complex
     * 
     */
    @XmlEnumValue("high")
    HIGH("high");
    private final String value;

    RatingEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RatingEnumType fromValue(String v) {
        for (RatingEnumType c: RatingEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
