//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package junk;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subUseEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="subUseEnumType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="value"/>
 *     &lt;enumeration value="title"/>
 *     &lt;enumeration value="legacy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "subUseEnumType")
@XmlEnum
public enum SubUseEnumType {


    /**
     * Replace with the selected <xccdf:value>
     *                         or <xccdf:complex-value> of an <xccdf:Value>.
     *                     
     * 
     */
    @XmlEnumValue("value")
    VALUE("value"),

    /**
     * Replace with the <xccdf:title> of the
     *                         <xccdf:Value>. 
     * 
     */
    @XmlEnumValue("title")
    TITLE("title"),

    /**
     * Use the context-dependent processing of
     *                         <xccdf:sub> elements outlined in XCCDF 1.1.4. 
     * 
     */
    @XmlEnumValue("legacy")
    LEGACY("legacy");
    private final String value;

    SubUseEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubUseEnumType fromValue(String v) {
        for (SubUseEnumType c: SubUseEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
