//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package junk;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 *  Data type for the <xccdf:Value> element, which
 *                 is a named parameter that can be substituted into properties of other elements
 *                 within the <xccdf:Benchmark>, including the interior of structured check
 *                 specifications and fix scripts. 
 * 
 * <p>Java class for valueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="valueType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://checklists.nist.gov/xccdf/1.2}itemType">
 *       &lt;sequence>
 *         &lt;choice maxOccurs="unbounded">
 *           &lt;element name="value" type="{http://checklists.nist.gov/xccdf/1.2}selStringType"/>
 *           &lt;element name="complex-value" type="{http://checklists.nist.gov/xccdf/1.2}selComplexValueType"/>
 *         &lt;/choice>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="default" type="{http://checklists.nist.gov/xccdf/1.2}selStringType"/>
 *           &lt;element name="complex-default" type="{http://checklists.nist.gov/xccdf/1.2}selComplexValueType"/>
 *         &lt;/choice>
 *         &lt;element name="match" type="{http://checklists.nist.gov/xccdf/1.2}selStringType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="lower-bound" type="{http://checklists.nist.gov/xccdf/1.2}selNumType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="upper-bound" type="{http://checklists.nist.gov/xccdf/1.2}selNumType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="choices" type="{http://checklists.nist.gov/xccdf/1.2}selChoicesType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="source" type="{http://checklists.nist.gov/xccdf/1.2}uriRefType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="signature" type="{http://checklists.nist.gov/xccdf/1.2}signatureType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://checklists.nist.gov/xccdf/1.2}valueIdType" />
 *       &lt;attribute name="type" type="{http://checklists.nist.gov/xccdf/1.2}valueTypeType" default="string" />
 *       &lt;attribute name="operator" type="{http://checklists.nist.gov/xccdf/1.2}valueOperatorType" default="equals" />
 *       &lt;attribute name="interactive" type="{http://www.w3.org/2001/XMLSchema}boolean" default="0" />
 *       &lt;attribute name="interfaceHint" type="{http://checklists.nist.gov/xccdf/1.2}interfaceHintType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "valueType", propOrder = {
    "valueOrComplexValue",
    "defaultOrComplexDefault",
    "match",
    "lowerBound",
    "upperBound",
    "choices",
})
public class ValueType
    extends ItemType
{

    @XmlElements({
        @XmlElement(name = "value", type = SelStringType.class),
        @XmlElement(name = "complex-value", type = SelComplexValueType.class)
    })
    protected List<Object> valueOrComplexValue;
    @XmlElements({
        @XmlElement(name = "default", type = SelStringType.class),
        @XmlElement(name = "complex-default", type = SelComplexValueType.class)
    })
    protected List<Object> defaultOrComplexDefault;
    protected List<SelStringType> match;
    @XmlElement(name = "lower-bound")
    protected List<SelNumType> lowerBound;
    @XmlElement(name = "upper-bound")
    protected List<SelNumType> upperBound;
    protected List<SelChoicesType> choices;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;
    @XmlAttribute(name = "type")
    protected ValueTypeType type;
    @XmlAttribute(name = "operator")
    protected ValueOperatorType operator;
    @XmlAttribute(name = "interactive")
    protected Boolean interactive;

    /**
     * Gets the value of the valueOrComplexValue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the valueOrComplexValue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValueOrComplexValue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelStringType }
     * {@link SelComplexValueType }
     * 
     * 
     */
    public List<Object> getValueOrComplexValue() {
        if (valueOrComplexValue == null) {
            valueOrComplexValue = new ArrayList<Object>();
        }
        return this.valueOrComplexValue;
    }

    /**
     * Gets the value of the defaultOrComplexDefault property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultOrComplexDefault property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultOrComplexDefault().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelStringType }
     * {@link SelComplexValueType }
     * 
     * 
     */
    public List<Object> getDefaultOrComplexDefault() {
        if (defaultOrComplexDefault == null) {
            defaultOrComplexDefault = new ArrayList<Object>();
        }
        return this.defaultOrComplexDefault;
    }

    /**
     * Gets the value of the match property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the match property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatch().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelStringType }
     * 
     * 
     */
    public List<SelStringType> getMatch() {
        if (match == null) {
            match = new ArrayList<SelStringType>();
        }
        return this.match;
    }

    /**
     * Gets the value of the lowerBound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lowerBound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLowerBound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelNumType }
     * 
     * 
     */
    public List<SelNumType> getLowerBound() {
        if (lowerBound == null) {
            lowerBound = new ArrayList<SelNumType>();
        }
        return this.lowerBound;
    }

    /**
     * Gets the value of the upperBound property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the upperBound property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUpperBound().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelNumType }
     * 
     * 
     */
    public List<SelNumType> getUpperBound() {
        if (upperBound == null) {
            upperBound = new ArrayList<SelNumType>();
        }
        return this.upperBound;
    }

    /**
     * Gets the value of the choices property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the choices property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getChoices().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SelChoicesType }
     * 
     * 
     */
    public List<SelChoicesType> getChoices() {
        if (choices == null) {
            choices = new ArrayList<SelChoicesType>();
        }
        return this.choices;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ValueTypeType }
     *     
     */
    public ValueTypeType getType() {
        if (type == null) {
            return ValueTypeType.STRING;
        } else {
            return type;
        }
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueTypeType }
     *     
     */
    public void setType(ValueTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link ValueOperatorType }
     *     
     */
    public ValueOperatorType getOperator() {
        if (operator == null) {
            return ValueOperatorType.EQUALS;
        } else {
            return operator;
        }
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueOperatorType }
     *     
     */
    public void setOperator(ValueOperatorType value) {
        this.operator = value;
    }

    /**
     * Gets the value of the interactive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isInteractive() {
        if (interactive == null) {
            return false;
        } else {
            return interactive;
        }
    }

    /**
     * Sets the value of the interactive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInteractive(Boolean value) {
        this.interactive = value;
    }

}
