//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.06 at 04:58:26 PM CDT 
//


package xccdfConvert;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

@XmlAccessorType(XmlAccessType.FIELD)

@XmlRootElement(name = "VulnData")
public class VulnData {
	@XmlElement(name = "VulnDiscussion")
    protected String vulndiscuss;
	@XmlElement(name = "FalsePositives")
    protected String false_positive;
	@XmlElement(name = "FalseNegatives")
    protected String false_negative;
	@XmlElement(name = "Documentable")
    protected boolean documentable;
	@XmlElement(name = "Mitigations")
    protected String mitigations;
	@XmlElement(name = "SeverityOverrideGuidance")
    protected String severity_override;
	@XmlElement(name = "PotentialImpacts")
    protected String impacts;
	@XmlElement(name = "ThirdPartyTools")
    protected String thirdparty;
	@XmlElement(name = "MitigationControl")
    protected String mitigation_control;
	@XmlElement(name = "Responsibility")
    protected String responsibility;
	@XmlElement(name = "IAControls")
    protected String iacontrols;
    
    public String getVulnDiscuss() {
        return (vulndiscuss == null? "" : this.vulndiscuss);
    }
    
    public String getFalsePositive() {
        return (false_positive == null? "" : this.false_positive);
    }
    
    public String getFalseNegative() {
        return (false_negative == null? "" : this.false_negative);
    }
    
    public boolean getDocumentable() {
        return this.documentable;
    }
    
    public String getMitigations() {
        return (mitigations == null? "" : this.mitigations);
    }
    
    public String getSeverityOverride() {
        return (severity_override == null? "" : this.severity_override);
    }
    
    public String getImpacts() {
        return (impacts == null? "" : this.impacts);
    }
    
    public String getThirdParty() {
        return (thirdparty == null? "" : this.thirdparty);
    }
    
    public String getMitigationControl() {
        return (mitigation_control == null? "" : this.mitigation_control);
    }
    
    public String getResponsibility() {
        return (responsibility == null? "" : this.responsibility);
    }
    
    public String getIAControls() {
        return (iacontrols == null? "" : this.iacontrols);
    }

}
