//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.02 at 06:54:38 PM CDT 
//


package checklist;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _COMMENTS_QNAME = new QName("", "COMMENTS");
    private final static QName _TECHAREA_QNAME = new QName("", "TECH_AREA");
    private final static QName _SIDNAME_QNAME = new QName("", "SID_NAME");
    private final static QName _TARGETKEY_QNAME = new QName("", "TARGET_KEY");
    private final static QName _ROLE_QNAME = new QName("", "ROLE");
    private final static QName _VULNATTRIBUTE_QNAME = new QName("", "VULN_ATTRIBUTE");
    private final static QName _TARGETCOMMENT_QNAME = new QName("", "TARGET_COMMENT");
    private final static QName _STATUS_QNAME = new QName("", "STATUS");
    private final static QName _FINDINGDETAILS_QNAME = new QName("", "FINDING_DETAILS");
    private final static QName _SEVERITYJUSTIFICATION_QNAME = new QName("", "SEVERITY_JUSTIFICATION");
    private final static QName _HOSTGUID_QNAME = new QName("", "HOST_GUID");
    private final static QName _STIGGUID_QNAME = new QName("", "STIG_GUID");
    private final static QName _ATTRIBUTEDATA_QNAME = new QName("", "ATTRIBUTE_DATA");
    private final static QName _HOSTNAME_QNAME = new QName("", "HOST_NAME");
    private final static QName _HOSTIP_QNAME = new QName("", "HOST_IP");
    private final static QName _WEBORDATABASE_QNAME = new QName("", "WEB_OR_DATABASE");
    private final static QName _SIDDATA_QNAME = new QName("", "SID_DATA");
    private final static QName _ASSETTYPE_QNAME = new QName("", "ASSET_TYPE");
    private final static QName _HOSTMAC_QNAME = new QName("", "HOST_MAC");
    private final static QName _WEBDBINSTANCE_QNAME = new QName("", "WEB_DB_INSTANCE");
    private final static QName _SEVERITYOVERRIDE_QNAME = new QName("", "SEVERITY_OVERRIDE");
    private final static QName _HOSTFQDN_QNAME = new QName("", "HOST_FQDN");
    private final static QName _WEBDBSITE_QNAME = new QName("", "WEB_DB_SITE");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ISTIG }
     * 
     */
    public ISTIG createISTIG() {
        return new ISTIG();
    }

    /**
     * Create an instance of {@link STIGINFO }
     * 
     */
    public STIGINFO createSTIGINFO() {
        return new STIGINFO();
    }

    /**
     * Create an instance of {@link SIDATA }
     * 
     */
    public SIDATA createSIDATA() {
        return new SIDATA();
    }

    /**
     * Create an instance of {@link VULN }
     * 
     */
    public VULN createVULN() {
        return new VULN();
    }

    /**
     * Create an instance of {@link STIGDATA }
     * 
     */
    public STIGDATA createSTIGDATA() {
        return new STIGDATA();
    }

    /**
     * Create an instance of {@link STIGS }
     * 
     */
    public STIGS createSTIGS() {
        return new STIGS();
    }

    /**
     * Create an instance of {@link CHECKLIST }
     * 
     */
    public CHECKLIST createCHECKLIST() {
        return new CHECKLIST();
    }

    /**
     * Create an instance of {@link ASSET }
     * 
     */
    public ASSET createASSET() {
        return new ASSET();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "COMMENTS")
    public JAXBElement<String> createCOMMENTS(String value) {
        return new JAXBElement<String>(_COMMENTS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TECH_AREA")
    public JAXBElement<String> createTECHAREA(String value) {
        return new JAXBElement<String>(_TECHAREA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SID_NAME")
    public JAXBElement<String> createSIDNAME(String value) {
        return new JAXBElement<String>(_SIDNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TARGET_KEY")
    public JAXBElement<String> createTARGETKEY(String value) {
        return new JAXBElement<String>(_TARGETKEY_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ROLE")
    public JAXBElement<String> createROLE(String value) {
        return new JAXBElement<String>(_ROLE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VULN_ATTRIBUTE")
    public JAXBElement<String> createVULNATTRIBUTE(String value) {
        return new JAXBElement<String>(_VULNATTRIBUTE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TARGET_COMMENT")
    public JAXBElement<String> createTARGETCOMMENT(String value) {
        return new JAXBElement<String>(_TARGETCOMMENT_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STATUS")
    public JAXBElement<String> createSTATUS(String value) {
        return new JAXBElement<String>(_STATUS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FINDING_DETAILS")
    public JAXBElement<String> createFINDINGDETAILS(String value) {
        return new JAXBElement<String>(_FINDINGDETAILS_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEVERITY_JUSTIFICATION")
    public JAXBElement<String> createSEVERITYJUSTIFICATION(String value) {
        return new JAXBElement<String>(_SEVERITYJUSTIFICATION_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_GUID")
    public JAXBElement<String> createHOSTGUID(String value) {
        return new JAXBElement<String>(_HOSTGUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "STIG_GUID")
    public JAXBElement<String> createSTIGGUID(String value) {
        return new JAXBElement<String>(_STIGGUID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ATTRIBUTE_DATA")
    public JAXBElement<String> createATTRIBUTEDATA(String value) {
        return new JAXBElement<String>(_ATTRIBUTEDATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_NAME")
    public JAXBElement<String> createHOSTNAME(String value) {
        return new JAXBElement<String>(_HOSTNAME_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_IP")
    public JAXBElement<String> createHOSTIP(String value) {
        return new JAXBElement<String>(_HOSTIP_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WEB_OR_DATABASE")
    public JAXBElement<Boolean> createWEBORDATABASE(Boolean value) {
        return new JAXBElement<Boolean>(_WEBORDATABASE_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SID_DATA")
    public JAXBElement<String> createSIDDATA(String value) {
        return new JAXBElement<String>(_SIDDATA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ASSET_TYPE")
    public JAXBElement<String> createASSETTYPE(String value) {
        return new JAXBElement<String>(_ASSETTYPE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_MAC")
    public JAXBElement<String> createHOSTMAC(String value) {
        return new JAXBElement<String>(_HOSTMAC_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WEB_DB_INSTANCE")
    public JAXBElement<String> createWEBDBINSTANCE(String value) {
        return new JAXBElement<String>(_WEBDBINSTANCE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SEVERITY_OVERRIDE")
    public JAXBElement<String> createSEVERITYOVERRIDE(String value) {
        return new JAXBElement<String>(_SEVERITYOVERRIDE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "HOST_FQDN")
    public JAXBElement<String> createHOSTFQDN(String value) {
        return new JAXBElement<String>(_HOSTFQDN_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WEB_DB_SITE")
    public JAXBElement<String> createWEBDBSITE(String value) {
        return new JAXBElement<String>(_WEBDBSITE_QNAME, String.class, null, value);
    }

}
