//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.09.02 at 06:54:38 PM CDT 
//


package checklist;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SID_NAME"/>
 *         &lt;element ref="{}SID_DATA" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sidname",
    "siddata"
})
@XmlRootElement(name = "SI_DATA")
public class SIDATA {

    @XmlElement(name = "SID_NAME", required = true)
    protected String sidname;
    @XmlElement(name = "SID_DATA")
    protected String siddata;
    
    public SIDATA(String name, String value) {
		this.sidname = name;
		this.siddata = value;
	}

    public SIDATA() {
		// TODO Auto-generated constructor stub
	}

	/**
     * Gets the value of the sidname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIDNAME() {
        return sidname;
    }

    /**
     * Sets the value of the sidname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIDNAME(String value) {
        this.sidname = value;
    }

    /**
     * Gets the value of the siddata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSIDDATA() {
        return siddata;
    }

    /**
     * Sets the value of the siddata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSIDDATA(String value) {
        this.siddata = value;
    }

}
